name: jax-dit
channels:
    - defaults
dependencies:
    - python=3.10
    - pip
    - numpy
    - scipy
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - seaborn
    - mesalib
    - glew
    - glfw
    - Cython
    - conda-forge::opencv
    - pip:
        - jax[tpu]==0.4.14 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
        - numba
        - opt-einsum
        - numpy
        - absl-py
        - termcolor
        - matplotlib
        - ml-collections
        - cython<3
        - wandb
        - imageio
        - libtmux
        - threadpoolctl==3.1.0
        - plotly
        - tabulate
        - tensorflow-cpu
        - tensorflow-probability==0.22.0
        - tensorflow-datasets
        - flax==0.7.4
        - optax==0.1.7
        - orbax==0.1.9
        - distrax==0.1.4
        - chex==0.1.82

